import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function truthyAny(...keys: string[]) {
  return keys.some(truthy)
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const CLICKZETTA_EXPERIMENTAL = truthy("CLICKZETTA_EXPERIMENTAL")
const copy = process.env["CLICKZETTA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  CLICKZETTA_AUTO_SHARE: truthy("CLICKZETTA_AUTO_SHARE"),
  CLICKZETTA_AUTO_HEAP_SNAPSHOT: truthy("CLICKZETTA_AUTO_HEAP_SNAPSHOT"),
  CLICKZETTA_GIT_BASH_PATH: process.env["CLICKZETTA_GIT_BASH_PATH"],
  CLICKZETTA_CONFIG: process.env["CLICKZETTA_CONFIG"],
  CLICKZETTA_CONFIG_CONTENT: process.env["CLICKZETTA_CONFIG_CONTENT"],
  CLICKZETTA_DISABLE_AUTOUPDATE: truthy("CLICKZETTA_DISABLE_AUTOUPDATE"),
  CLICKZETTA_ALWAYS_NOTIFY_UPDATE: truthy("CLICKZETTA_ALWAYS_NOTIFY_UPDATE"),
  CLICKZETTA_DISABLE_PRUNE: truthy("CLICKZETTA_DISABLE_PRUNE"),
  CLICKZETTA_DISABLE_TERMINAL_TITLE: truthy("CLICKZETTA_DISABLE_TERMINAL_TITLE"),
  CLICKZETTA_SHOW_TTFD: truthy("CLICKZETTA_SHOW_TTFD"),
  CLICKZETTA_PERMISSION: process.env["CLICKZETTA_PERMISSION"],
  CLICKZETTA_DISABLE_DEFAULT_PLUGINS: truthyAny(
    "CLICKZETTA_DISABLE_DEFAULT_PLUGINS",
    "OPENCODE_DISABLE_DEFAULT_PLUGINS",
  ),
  CLICKZETTA_DISABLE_LSP_DOWNLOAD: truthy("CLICKZETTA_DISABLE_LSP_DOWNLOAD"),
  CLICKZETTA_ENABLE_EXPERIMENTAL_MODELS: truthy("CLICKZETTA_ENABLE_EXPERIMENTAL_MODELS"),
  CLICKZETTA_DISABLE_AUTOCOMPACT: truthy("CLICKZETTA_DISABLE_AUTOCOMPACT"),
  CLICKZETTA_DISABLE_MODELS_FETCH: truthy("CLICKZETTA_DISABLE_MODELS_FETCH"),
  CLICKZETTA_DISABLE_MOUSE: truthy("CLICKZETTA_DISABLE_MOUSE"),
  CLICKZETTA_FAKE_VCS: process.env["CLICKZETTA_FAKE_VCS"],
  CLICKZETTA_SERVER_PASSWORD: process.env["CLICKZETTA_SERVER_PASSWORD"],
  CLICKZETTA_SERVER_USERNAME: process.env["CLICKZETTA_SERVER_USERNAME"],
  CLICKZETTA_ENABLE_QUESTION_TOOL: truthy("CLICKZETTA_ENABLE_QUESTION_TOOL"),

  // Experimental
  CLICKZETTA_EXPERIMENTAL,
  CLICKZETTA_EXPERIMENTAL_FILEWATCHER: Config.boolean("CLICKZETTA_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CLICKZETTA_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CLICKZETTA_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CLICKZETTA_EXPERIMENTAL_ICON_DISCOVERY: CLICKZETTA_EXPERIMENTAL || truthy("CLICKZETTA_EXPERIMENTAL_ICON_DISCOVERY"),
  CLICKZETTA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CLICKZETTA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  CLICKZETTA_ENABLE_EXA: truthy("CLICKZETTA_ENABLE_EXA") || CLICKZETTA_EXPERIMENTAL || truthy("CLICKZETTA_EXPERIMENTAL_EXA"),
  CLICKZETTA_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("CLICKZETTA_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  CLICKZETTA_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("CLICKZETTA_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  CLICKZETTA_EXPERIMENTAL_OXFMT: CLICKZETTA_EXPERIMENTAL || truthy("CLICKZETTA_EXPERIMENTAL_OXFMT"),
  CLICKZETTA_EXPERIMENTAL_LSP_TY: truthy("CLICKZETTA_EXPERIMENTAL_LSP_TY"),
  CLICKZETTA_EXPERIMENTAL_LSP_TOOL: CLICKZETTA_EXPERIMENTAL || truthy("CLICKZETTA_EXPERIMENTAL_LSP_TOOL"),
  CLICKZETTA_DISABLE_FILETIME_CHECK: Config.boolean("CLICKZETTA_DISABLE_FILETIME_CHECK").pipe(Config.withDefault(false)),
  CLICKZETTA_EXPERIMENTAL_PLAN_MODE: CLICKZETTA_EXPERIMENTAL || truthy("CLICKZETTA_EXPERIMENTAL_PLAN_MODE"),
  CLICKZETTA_EXPERIMENTAL_MARKDOWN: !falsy("CLICKZETTA_EXPERIMENTAL_MARKDOWN"),
  CLICKZETTA_MODELS_URL: process.env["CLICKZETTA_MODELS_URL"],
  CLICKZETTA_MODELS_PATH: process.env["CLICKZETTA_MODELS_PATH"],
  CLICKZETTA_DISABLE_EMBEDDED_WEB_UI: truthy("CLICKZETTA_DISABLE_EMBEDDED_WEB_UI"),
  CLICKZETTA_DB: process.env["CLICKZETTA_DB"],
  CLICKZETTA_DISABLE_CHANNEL_DB: truthy("CLICKZETTA_DISABLE_CHANNEL_DB"),
  CLICKZETTA_SKIP_MIGRATIONS: truthy("CLICKZETTA_SKIP_MIGRATIONS"),
  CLICKZETTA_STRICT_CONFIG_DEPS: truthy("CLICKZETTA_STRICT_CONFIG_DEPS"),

  CLICKZETTA_WORKSPACE_ID: process.env["CLICKZETTA_WORKSPACE_ID"],
  CLICKZETTA_EXPERIMENTAL_HTTPAPI: CLICKZETTA_EXPERIMENTAL || truthy("CLICKZETTA_EXPERIMENTAL_HTTPAPI"),
  CLICKZETTA_EXPERIMENTAL_WORKSPACES: CLICKZETTA_EXPERIMENTAL || truthy("CLICKZETTA_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get CLICKZETTA_DISABLE_PROJECT_CONFIG() {
    return truthy("CLICKZETTA_DISABLE_PROJECT_CONFIG")
  },
  get CLICKZETTA_TUI_CONFIG() {
    return process.env["CLICKZETTA_TUI_CONFIG"]
  },
  get CLICKZETTA_CONFIG_DIR() {
    return process.env["CLICKZETTA_CONFIG_DIR"]
  },
  get CLICKZETTA_PURE() {
    return truthy("CLICKZETTA_PURE")
  },
  get CLICKZETTA_PLUGIN_META_FILE() {
    return process.env["CLICKZETTA_PLUGIN_META_FILE"]
  },
  get CLICKZETTA_CLIENT() {
    return process.env["CLICKZETTA_CLIENT"] ?? "cli"
  },
}
